added emailMessage maintain functionality
OC-ComputerScience/accommodation-frontend pull request #17
Opened 2024-02-24 01:38 UTC by sollydg

2024-03-01 16:47 UTC, JonathanBooker912 requested changes
Everything works functionally, just some style changes. Check the failed test on agility if you need a visual for what I mean about the buttons.

2024-03-01 16:47 UTC, JonathanBooker912 commented on src/views/AdminEmailManage.vue
> +                    <v-btn class="mr-4" color="button_blue" style="float:right" @click="editEmail(a.emailMessageId)">edit</v-btn>
Place these in a "v-row" so they display side-by-side

2024-03-01 16:47 UTC, JonathanBooker912 commented on src/views/AdminEmailAdd.vue
> +                <v-text-field class="pl-5 pr-5" label="enter the content of the email" v-model="emailText"></v-text-field>
- Change labels to remove "enter" verbage (ie. "enter description"
- If the labels are redundant with the <p> tags above the fields, change the labels to provide more useful information, or remove them to be consistent

2024-03-01 16:47 UTC, JonathanBooker912 commented on src/views/AdminEmailEdit.vue
> +            </div>
Change the labels here too

2024-03-08 22:10 UTC, DarkoPrime approved these changes

2024-03-08 22:11 UTC, merged